services:
  rl-envs-api:
    build:
      context: .
      dockerfile: rl-envs-service/Dockerfile
    container_name: rl_envs_api
    ports:
      - "8001:8001"
    volumes:
      - ./rl-envs-service/openapi_spec:/app/openapi_spec
      - ./rl-envs-service/artifacts:/app/artifacts
    env_file:
      - ./rl-envs-service/.env

  tests:
    profiles: ["test"]
    build:
      context: .
      dockerfile: rl-envs-service/Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
    entrypoint:
      - sh
      - -c
      - |
        python -m pip install --no-cache-dir -r rl-envs-service/requirements-dev.txt &&
        python -m pytest

